from langchain_openai import ChatOpenAI
from langchain.prompts import ChatPromptTemplate
from dotenv import load_dotenv

import sqlite3

# load all the keys from .env file
load_dotenv()

# create llm
# llm = ChatOpenAI(model="gpt-5")
llm = ChatOpenAI(model="google/gemma-3-12b", base_url="http://localhost:1234/v1")

generate_query_template = """
You are an expert database engineer having good experience in writing complex SQL queries.
Generate SQL query based on the question asked by user.
Use the schema provided here.

Question: {question}
Schema: {schema}

Query:

Generate the query only. Nothing else. Do not use markdown format. Use plain text.
"""

generate_final_answer_template = """
You are an expert database summarizer.
You can find the question asked by user, result of the query and database schema here.
Answer the question by formatting the database result.

Question: {question}

Schema: {schema}

Database Result: {result}

Formatted result: 
"""

db_schema = """
    CREATE TABLE students(
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        name TEXT,
        city TEXT,
        subject TEXT,
        marks INT
    );
"""

def execute_query(query):
    # create sqlite connection
    connection = sqlite3.connect("students.db")

    # get the data from table
    cursor = connection.cursor()

    # execute the query
    cursor.execute(query)

    # get the data
    data = cursor.fetchall()

    # close the connection
    connection.close()

    return data


# create the prompt template
prompt_template = ChatPromptTemplate.from_template(template=generate_query_template)

while True:
    # get question from user
    question = input("question> ")
    if question == "exit":
        break

    # create the prompt
    prompt = prompt_template.invoke({
        "question": question,
        "schema": db_schema
    })

    # send the prompt and get the result
    result = llm.invoke(prompt)

    # read the query generated by LLM
    query = result.content

    # execute the query and get the result
    db_result = execute_query(query=query)
    print(db_result)

    # get the formatted result as per the question
    prompt_template = ChatPromptTemplate.from_template(template=generate_final_answer_template)
    prompt = prompt_template.invoke({
        "question": question,
        "result": db_result,
        "schema": db_schema
    })
    result = llm.invoke(prompt)
    print(result.content)

